apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-triggers.fullname" . }}-controller
  labels:
    app: tekton-triggers-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-triggers
    app.kubernetes.io/version: v0.20.1
    triggers.tekton.dev/release: v0.20.1
    version: v0.20.1
  {{- include "tekton-triggers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.type }}
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.controller.ports | toYaml | nindent 2 -}}
