apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-triggers.fullname" . }}-triggers-info
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.labels" . | nindent 4 }}
data:
  version: {{ .Values.triggersInfo.version | quote }}
