apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tekton-triggers.fullname" . }}-triggers-webhook-certs
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.20.1
  {{- include "tekton-triggers.labels" . | nindent 4 }}
