apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-triggers.fullname" . }}-webhook
  labels:
    app: tekton-triggers-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: webhook
    app.kubernetes.io/part-of: tekton-triggers
    app.kubernetes.io/version: v0.20.1
    triggers.tekton.dev/release: v0.20.1
    version: v0.20.1
  {{- include "tekton-triggers.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.type }}
  selector:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: webhook
    app.kubernetes.io/part-of: tekton-triggers
  {{- include "tekton-triggers.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.ports | toYaml | nindent 2 -}}
