# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "tekton_pipelines.fullname". }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
{{ include "tekton_pipelines.labels" . | indent 4 }}
    pipeline.tekton.dev/release: {{ .Chart.AppVersion | quote }}
    version: {{ .Chart.AppVersion | quote }}
spec:
  minReplicas: {{ .Values.webhook_autoscaler.minReplicas}}
  maxReplicas: {{ .Values.webhook_autoscaler.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tekton-pipelines-webhook
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 100
