---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelines-controller-leaderelection
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: controller
{{- template "tekton.labels" }}
subjects:
  - kind: ServiceAccount
    name: tekton-pipelines-controller
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: tekton-pipelines-leader-election
  apiGroup: rbac.authorization.k8s.io
