---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: webhook
{{- template "tekton.labels" }}
    pipeline.tekton.dev/release: "v0.32.1"

# The data is populated at install time.
