---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
{{ include "tekton.labels" . | indent 4 }}
    pipeline.tekton.dev/release: {{ .Values.release | quote }}
    app: tekton-pipelines-webhook
    version: {{ .Values.version | quote }}
  name: tekton-pipelines-webhook
  namespace: {{ .Values.namespace }}
spec:
  ports:
{{ .Values.webhook_service.ports | toYaml | indent 4 }}
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
{{ include "tekton.labels" . | indent 4 }}
