---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.pipeline.tekton.dev
  labels:
    app.kubernetes.io/component: webhook
{{- template "tekton.labels" }}
    pipeline.tekton.dev/release: "v0.32.1"
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: tekton-pipelines-webhook
        namespace: {{ .Values.namespace }}
    failurePolicy: Fail
    sideEffects: None
    name: validation.webhook.pipeline.tekton.dev
