apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  name: {{ include "tekton-interceptors.fullname" . }}-github
  labels:
  {{- include "tekton-interceptors.labels" . | nindent 4 }}
spec:
  clientConfig:
    service:
      name: tekton-triggers-core-interceptors
      namespace: tekton-pipelines
      path: github
      port: 8443
