apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tekton-interceptors.fullname" . }}-tekton-triggers-core-interceptors-certs
  labels:
    app.kubernetes.io/component: interceptors
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: core-interceptors
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.20.1
  {{- include "tekton-interceptors.labels" . | nindent 4 }}
